{{- range .Values.heket.apps }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .namespace | default .name | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name | quote }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .namespace | default .name | quote }}
    server: {{ .server | default $.Values.heket.defaults.server }}
  project: {{ .project | default "default" }}
  source:
    path: {{ .path | default "." | quote }}
    repoURL: {{ .repoURL | default $.Values.heket.defaults.repoURL | quote }}
    targetRevision: {{ .targetRevision | default "HEAD" | quote }}
{{- end }}
