# Install Custom Ressource Definitions?
installCRDs: true

# Default values for your applications
defaults:
  project: "default"
  repoURL: https://github.com/nold360/heqet
  server: https://kubernetes.default.svc
  automated:
    prune: true
    selfHeal: false

# Heqet Functions / Injectors:
generators:
  # Nginx Ingress & Cert Manager TLS Injector
  ingress:
    enabled: true
 
    # ACME / Letsencrypt Injector
    acme:
      enabled: true
      server:
      email: nold@gnu.one


  # Vault Secret Injector
  # incl. ServiceAccount read-only ["ro"]
  vault:
    enabled: true
    createServiceAccount: true
    defaultPermissions: "ro"

# annotations:
commonAnnotations:
  enabled: false # to code...


# App Definitions
apps:
  - name: heqet
    noValues: true

  - name: argocd
    repoURL: https://github.com/argoproj/argo-helm
    path: charts/argo-cd
    vhost: argocd.heqet.gnu.one
    ingress: server
    vault: server

    # for pod annotations / vault/ ...
    podSpecRoots:
      - server
    
  - name: jaeger
    repoURL: https://github.com/jaegertracing/helm-charts
    path: charts/jaeger
    targetRevision: HEAD
    vhost: jaeger.heqet.gnu.one
    ingress: query

  - name: nginx-ingress
    repoURL: https://github.com/kubernetes/ingress-nginx
    path: charts/ingress-nginx

  - name: cert-manager
    repoURL: https://github.com/jetstack/cert-manager
    path: deploy/charts/cert-manager
 
  - name: vault
    repoURL: https://github.com/hashicorp/vault-helm
    vhost: vault.heqet.gnu.one
    ingress: server
    ingressHostsKeymap: true
    ignoreDifferences: |
      - group: apiextensions.k8s.io
        kind: CustomResourceDefinition
        jsonPointers:
          - /metadata/annotations
          - /metadata/labels
          - /spec/validation
      - group: admissionregistration.k8s.io
        kind: MutatingWebhookConfiguration
        jsonPointers:
          - /webhooks
      - group: admissionregistration.k8s.io
        kind: ValidatingWebhookConfiguration
        jsonPointers:
          - /webhooks

  - name: kubernetes-dashboard
    repoURL: https://github.com/helm/charts
    path: stable/kubernetes-dashboard
    vhost: dashboard.heqet.gnu.one

  - name: loki-stack
    repoURL: https://github.com/grafana/loki
    path: production/helm/loki-stack
