# Install Custom Ressource Definitions?
installCRDs: true

# Default values that are used for creating ArgoCD `Application` definitions
defaults:
  project: "heqet"
  server: https://kubernetes.default.svc
  automated:
    prune: true
    selfHeal: false

# Heqet Functions / Injectors:
generators:
  # Vault Secret Injector
  vault: true

  # Use predfined NetworkPolices in Apps/Namespaces
  networkpolicy: true

# Define your NetworkPolicies here
networkpolicies:
  # Allow DNS to all Namespaces, deny everything else
  allow-dns:
    podSelector: {}
    policyTypes:
    - Egress
    egress:
    - ports:
      - port: 53
        protocol: UDP
      to:
      - namespaceSelector: {}

  # Allow access to internet proxy
  allow-proxy:
    podSelector: {}
    policyTypes:
    - Egress
    egress:
    - ports:
      - port: 80
        protocol: TCP
      - port: 3128
        protocol: TCP
      to:
      - namespaceSelector:
          matchLabels:
            app.heqet.gnu.one/name: proxy


# App Definitions that will be managed in ArgoCD
apps:
  # Heqet
  - name: heqet
    path: .
    repoURL: https://github.com/nold360/heqet
    targetRevision: test
    syncWave: "-1"
    selfHeal: true

  # ArgoCD - Continous Deployment from Git
  - name: argocd
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 3.10.0
    syncWave: "0"
    secrets:
      - name: argocd-secret
        keys:
          - admin.password
          - server.secretkey
          - oidc.auth0.clientSecret
   
  # Persistant Storage Local-Path Provosioner
  - name: slow-storage
    repoURL: https://github.com/rancher/local-path-provisioner
    path: deploy/chart
    syncWave: "0"
    parameters:
      - name: storageClass.name
        value: slow
      - name: nodePathMap[0].node
        value: DEFAULT_PATH_FOR_NON_LISTED_NODES
      - name: nodePathMap[0].paths[0]
        value: /data/kubernetes/storage

  # Metal LoadBalancer
  - name: metallb
    repoURL: https://charts.bitnami.com/bitnami
    chart: metallb
    targetRevision: 2.4.5
    syncWave: "0"

  - name: cert-manager
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: 1.4.1
    parameters:
      - name: installCRDs
        value: "true"
    secrets:
      - name: cert-manager-vault-approle
        keys:
          - secretId

  # NGINX Ingress - Internal
  - name: ingress-internal
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 3.34.0
    syncWave: "0"

  # NGINX Ingress - External
  - name: ingress-external
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 3.34.0
    syncWave: "0"

  # Squid Internet Proxy
  - name: proxy
    repoURL: http://honestica.github.io/lifen-charts
    chart: squid
    targetRevision: 0.3.0

  # Vault
  - name: vault
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.11.0
    syncWave: "-3"
    parameters:
      - name: ui.enabled
        value: "true"
      - name: global.psp.enabled
        value: "true"
      - name: server.networkPolicy.enabled
        value: "true"
      - name: server.dev.enabled
        value: "false"
      - name: standalone.enabled
        value: "true"

  # Vault Secret Operator for automatic Secret injection
  - name: vault-secrets-operator
    repoURL: https://ricoberger.github.io/helm-charts
    chart: vault-secrets-operator
    targetRevision: 1.15.0
    syncWave: "-2"

  # Keycloak Auth
  - name: keycloak
    repoURL: https://charts.bitnami.com/bitnami
    chart: keycloak
    targetRevision: 2.4.8
    ignoreDiff:
    - kind: Secret
      group: ""
      name: "keycloak.dc-tls"
      jsonPointers:
      - /data/ca.crt
      - /data/tls.crt
      - /data/tls.key
      - /metadata
    secrets:
    - name: passwords
      keys:
      - adminPassword
      - databasePassword
      - managementPassword
      - tlsKeystorePassword
      - tlsTruststorePassword
    - name: postgres
      keys:
      - "postgresql-password"
      - "postgresql-postgres-password"
    
  # Prometheus / Loki / Grafana / Promtail Stack for Logging & Metrics
  - name: prometheus
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 13.8.0
 
  - name: loki-stack
    repoURL: https://grafana.github.io/helm-charts
    chart: loki-stack
    existingNamespace: prometheus
    targetRevision: 2.4.1
    secrets:
      - name: loki-stack-grafana
        keys:
          - admin-user
          - admin-password
      - name: grafana-env
        keys:
          - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET

  # Container Registry
  - name: harbor
    repoURL: https://charts.bitnami.com/bitnami
    chart: harbor
    targetRevision: 9.8.3

  # Object Storage
  - name: minio
    repoURL: https://charts.bitnami.com/bitnami
    chart: minio
    targetRevision: 6.7.2
    ignoreDiff:
    - group: ""
      name: minio.dc-tls
      kind: Secret
      namespace: minio
      jsonPointers:
        - /data/ca.crt
        - /data/tls.crt
        - /data/tls.key
        - /metadata
    secrets:
      - name: minio-secret
        keys:
          - access-key
          - secret-key
 
  # PiHole
  - name: pihole
    repoURL: https://mojo2600.github.io/pihole-kubernetes
    chart: pihole
    targetRevision: 2.0.0
    secrets:
      - name: pihole-admin
        keys:
          - password

  # Backup Server
  - name: backup-lan
    repoURL: https://github.com/lib42/charts.git
    path: charts/borgserver
    targetRevision: dev

  - name: backup-dmz
    repoURL: https://github.com/lib42/charts.git
    path: charts/borgserver
    targetRevision: dev

  # Drone CI
  - name: drone
    repoURL: https://charts.drone.io
    chart: drone
    targetRevision: 0.1.7
    secrets:
      - name: drone-env
        keys:
          - DRONE_GITHUB_CLIENT_ID
          - DRONE_GITHUB_CLIENT_SECRET
          - DRONE_RPC_SECRET

  - name: drone-runner
    repoURL: https://charts.drone.io
    chart: drone-runner-kube
    targetRevision: 0.1.5
    secrets:
      - name: drone-env
        fromApp: drone
        keys:
          - DRONE_RPC_SECRET
    parameters:
      - name: extraSecretNamesForEnvFrom[0]
        value: "drone-env"
      - name: env.DRONE_NAMESPACE_DEFAULT
        value: drone-runner
      - name: env.DRONE_RPC_HOST
        value: drone.drone.svc.cluster.local
      - name: rbac.buildNamespaces[0]
        value: drone-runner

  # Apps...
  - name: folding
    #repoURL: https://pcktdmp.github.io/charts
    #chart: fahclient
    #targetRevision: 2.5.5
    repoURL: https://github.com/Nold360/charts-2/
    path: fahclient
    targetRevision: f_ingress
    parameters:
      - name: fahClient.user
        value: nold
      - name: fahClient.team
        value: "236833"
      - name: ingress.hostname
        value: folding.dc
      - name: ingress.enabled
        value: "true"
      - name: ingress.tls
        value: "true"
      - name: resources.limits.cpu
        value: "6"
      - name: resources.limits.memory
        value: 1Gi

  # Polaris - Scan cluster for stuff
  - name: polaris
    repoURL: https://charts.fairwinds.com/stable
    chart: polaris
    targetRevision: 3.1.1

  # Deluge & OpenVPN-Client
  - name: deluge
    repoURL: https://k8s-at-home.com/charts/
    chart: deluge
    targetRevision: 3.4.0
    secrets:
    - name: openvpn
      keys:
      - VPN_AUTH
      - vpnConfigfile

  # PyLoad Download Manager
  - name: pyload
    repoURL: https://k8s-at-home.com/charts/
    chart: pyload
    targetRevision: 4.4.1

  # Nextcloud - duh
  - name: nextcloud
    repoURL: https://nextcloud.github.io/helm
    chart: nextcloud
    targetRevision: 2.6.5
    networkpolicies:
      - allow-dns
      - allow-proxy
