# Install Custom Ressource Definitions?
installCRDs: true

# Default values that are used for creating ArgoCD `Application` definitions
defaults:
  project: "heqet"
  server: https://kubernetes.default.svc
  automated:
    prune: true
    selfHeal: false

# Heqet Functions / Injectors:
generators:
  # Vault Secret Injector
  vault: true

  # Use predfined NetworkPolices in Apps/Namespaces
  networkpolicy:
    enabled: true
    allowNamespace: true

# Define your NetworkPolicies here
networkpolicies:
  # Allow DNS to all Namespaces, deny everything else
  allow-dns:
    podSelector: {}
    policyTypes:
    - Egress
    egress:
    - ports:
      - port: 53
        protocol: UDP
      to:
      - namespaceSelector: {}

  allow-kubeapi:
    podSelector: {}
    policyTypes:
    - Egress
    egress:
    - ports:
      - port: 443
        protocol: TCP
      to:
      - namespaceSelector:
          matchLabels:
            name: kube-system

  # Allow access to internet proxy
  allow-proxy:
    podSelector: {}
    policyTypes:
    - Egress
    egress:
    - ports:
      - port: 80
        protocol: TCP
      - port: 3128
        protocol: TCP
      to:
      - namespaceSelector:
          matchLabels:
            app.heqet.gnu.one/name: proxy

  # Allow access from ingress-external
  allow-ingress:
    podSelector: {}
    policyTypes:
    - Ingress
    ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            app.heqet.gnu.one/name: ingress-external

  # Allow SSH for Gitea
  allow-ssh:
    podSelector: {}
    policyTypes:
    - Ingress
    ingress:
    - from:
      - ipBlock:
          cidr: 192.168.1.0/24
      ports:
      - port: 2222
        protocol: TCP

  # Allow Drone-Runner to access Drone
  allow-runner:
    podSelector: {}
    policyTypes:
    - Ingress
    ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            app.heqet.gnu.one/name: drone-runner

# App Definitions that will be managed in ArgoCD
apps:
  ## Infrastructure / Code Apps
  # Heqet
  - name: heqet
    path: .
    repoURL: https://git.nold.in/nold/heqet
    targetRevision: hive
    syncWave: "-1"
    selfHeal: true

  # ArgoCD - Continous Deployment from Git
  - name: argocd
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 3.11.1
    syncWave: "0"
    secrets:
      - name: argocd-secret
        keys:
          - admin.password
          - server.secretkey
          - oidc.auth0.clientSecret
   
  # Persistant Storage Local-Path Provosioner
  - name: fast-storage
    repoURL: https://github.com/rancher/local-path-provisioner
    path: deploy/chart
    syncWave: "0"
    parameters:
      - name: storageClass.name
        value: fast
      - name: nodePathMap[0].node
        value: DEFAULT_PATH_FOR_NON_LISTED_NODES
      - name: nodePathMap[0].paths[0]
        value: /var/lib/rancher/k3s/storage

  # Metal LoadBalancer
  - name: metallb
    repoURL: https://charts.bitnami.com/bitnami
    chart: metallb
    targetRevision: 2.4.5
    syncWave: "0"

  # Cert Manager Vault & ACME
  - name: cert-manager
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: 1.4.1
    parameters:
      - name: installCRDs
        value: "true"
    secrets:
      - name: cert-manager-vault-approle
        keys:
          - secretId

  # NGINX Ingress - Internal
  - name: ingress-internal
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 3.34.0
    syncWave: "0"

  # NGINX Ingress - External
  - name: ingress-external
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 3.34.0
    syncWave: "0"

  # Squid Internet Proxy
  - name: proxy
    repoURL: http://honestica.github.io/lifen-charts
    chart: squid
    targetRevision: 0.3.0

  # Vault
  - name: vault
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.14.0
    syncWave: "-3"
    parameters:
      - name: global.psp.enabled
        value: "true"
      - name: server.dev.enabled
        value: "false"

  # Vault Secret Operator for automatic Secret injection
  - name: vault-secrets-operator
    repoURL: https://ricoberger.github.io/helm-charts
    chart: vault-secrets-operator
    targetRevision: 1.15.0
    syncWave: "-2"

  # Prometheus / Loki / Grafana / Promtail Stack for Logging & Metrics
  - name: prometheus
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 13.8.0
 
  - name: loki-stack
    repoURL: https://grafana.github.io/helm-charts
    chart: loki-stack
    existingNamespace: prometheus
    targetRevision: 2.4.1
    secrets:
      - name: loki-stack-grafana
        keys:
          - admin-user
          - admin-password
      - name: grafana-env
        keys:
          - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET

  ## Security
  # Falco
  - name: falco
    repoURL: https://falcosecurity.github.io/charts
    chart: falco
    targetRevision: 1.15.7

  # Falco Exporter
  - name: falco-exporter
    disabled: true
    repoURL: https://falcosecurity.github.io/charts
    chart: falco-exporter
    targetRevision: 0.5.2

  ## Local Infrastructure Apps
  # Blocky DNS
  - name: blocky
    repoURL: https://k8s-at-home.com/charts
    chart: blocky
    targetRevision: 7.1.1

  # Backup Server
  - name: backup-lan
    repoURL: https://github.com/lib42/charts.git
    path: charts/borgserver
    targetRevision: dev

  ## Local Apps
  # Deluge & OpenVPN-Client
  - name: deluge
    repoURL: https://k8s-at-home.com/charts/
    chart: deluge
    targetRevision: 4.3.0
    secrets:
    - name: openvpn
      keys:
      - VPN_AUTH
      - vpnConfigfile

  # PyLoad Download Manager
  - name: pyload
    repoURL: https://k8s-at-home.com/charts/
    chart: pyload
    targetRevision: 4.4.1

  # Folding @ Home
  - name: folding
    repoURL: https://github.com/Nold360/charts-2/
    path: fahclient
    targetRevision: f_ingress
    parameters:
      - name: fahClient.user
        value: nold
      - name: fahClient.team
        value: "236833"
      - name: ingress.hostname
        value: folding.dc
      - name: ingress.enabled
        value: "true"
      - name: ingress.tls
        value: "true"
      - name: resources.limits.cpu
        value: "6"
      - name: resources.limits.memory
        value: 1Gi

  ### Public Apps
  # Nextcloud - duh
  - name: nextcloud
    repoURL: https://nextcloud.github.io/helm
    chart: nextcloud
    targetRevision: 2.6.5
    networkpolicies:
      - allow-dns
      - allow-proxy
      - allow-ingress
    secrets:
      - name: nextcloud-user
        keys:
        - username
        - password
        - smtp_username
        - smtp_password
      - name: nextcloud-postgres
        keys:
          - postgresql-username
          - postgresql-password
          - postgresql-postgres-password
      - name: nextcloud-db
        keys:
          - db-username
          - db-password

  # Gitea
  - name: gitea
    repoURL: https://dl.gitea.io/charts/
    chart: gitea
    targetRevision: 4.0.1
    networkpolicies:
      - allow-dns
      - allow-proxy
      - allow-ingress
      - allow-ssh
    secrets:
      - name: admin
        keys:
          - username
          - password
          - email
      - name: postgres
        keys:
          - postgresql-password
          - postgresql-postgres-password

  # Drone CI
  - name: drone
    repoURL: https://github.com/nold360/drone-charts.git
    path: charts/drone
    targetRevision: master
    secrets:
      - name: drone-env
        keys:
          - DRONE_GITEA_SERVER
          - DRONE_GITEA_CLIENT_ID
          - DRONE_GITEA_CLIENT_SECRET
          - DRONE_GITHUB_CLIENT_ID
          - DRONE_GITHUB_CLIENT_SECRET
          - DRONE_RPC_SECRET
    networkpolicies:
      - allow-dns
      - allow-proxy
      - allow-ingress
      - allow-runner

  - name: drone-runner
    repoURL: https://charts.drone.io
    chart: drone-runner-kube
    targetRevision: 0.1.5
    secrets:
      - name: drone-env
        fromApp: drone
        keys:
        - DRONE_RPC_SECRET
    parameters:
      - name: image.tag
        value: linux-amd64
      - name: extraSecretNamesForEnvFrom[0]
        value: "drone-env"
      - name: env.DRONE_NAMESPACE_DEFAULT
        value: drone-runner
      - name: env.DRONE_RPC_HOST
        value: drone.drone.svc.cluster.local
      - name: env.HTTP_PROXY
        value: http://proxy-squid.proxy.svc.cluster.local:80
      - name: env.HTTPS_PROXY
        value: http://proxy-squid.proxy.svc.cluster.local:80
      - name: env.NO_PROXY
        value: localhost,.cluster.local,drone,drone.drone.svc.cluster.local,10.0.0.0/8,10.42.0.1,10.43.0.1
      - name: rbac.buildNamespaces[0]
        value: drone-runner
      - name: env.DRONE_DEBUG
        value: "true"
      - name: env.DRONE_TRACE
        value: "true"
