# Install Custom Ressource Definitions?
installCRDs: false

# Default values that are used for creating ArgoCD `Application` definitions
defaults:
  project: "default"
  repoURL: https://github.com/nold360/heqet
  targetRevision: k3s
  server: https://kubernetes.default.svc
  automated:
    prune: true
    selfHeal: false
  domain: k3s

# Heqet Functions / Injectors:
generators:
  # Ingress & Cert Manager TLS Injector
  ingress:
    enabled: true
 
    # ACME / Letsencrypt Injector
    acme:
      enabled: false

      ## Default: https://acme-staging-v02.api.letsencrypt.org/directory
      ## Change to 'https://acme-v02.api.letsencrypt.org/directory' for real/trusted LE Certs
      #server: https://acme-v02.api.letsencrypt.org/directory
      email: nold@gnu.one


# App Definitions that will be managed in ArgoCD
apps:
  # Heqet
  - name: heqet
    path: .
    syncWave: "-1"
    noValues: true
    targetRevision: k3s
    vhost: hqt.k3s

  # SealedSecrests - Store encrypted secrets in git
  - name: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets/
    chart: sealed-secrets
    targetRevision: 1.15.0-r3
    syncWave: "-1"
    namespace: sealed-secrets

  # ArgoCD - Continous Deployment from Git
  - name: argocd
    repoURL: https://argoproj.github.io/argo-helm
    chart: argocd
    targetRevision: 3.0.0
    vhost: argocd.k3s
    ingress: server
    syncWave: "0"
    
  # Plain old Kubernetes Dashboard
  - name: kubernetes-dashboard
    disabled: true
    namespace: kube-system
    repoURL: https://github.com/nold360/charts
    path: stable/kubernetes-dashboard
    vhost: dashboard.k3s

  # Loki / Grafana / Promtail Stack for Logging & Metrics
  - name: loki-stack
    disabled: false
    repoURL: https://grafana.github.io/helm-charts
    chart: loki-stack
    targetRevision: 2.3.1
    vhost: grafana.k3s
    ingress: grafana

  # Polaris - Scan cluster for stuff
  - name: polaris
    repoURL: https://charts.fairwinds.com/stable
    chart: polaris
    targetRevision: 3.1.1
    ingress: dashboard
    namespace: polaris
    vhost: polaris.k3s
