# Install Custom Ressource Definitions?
installCRDs: false

# Default values that are used for creating ArgoCD `Application` definitions
defaults:
  project: "default"
  server: https://kubernetes.default.svc
  automated:
    prune: true
    selfHeal: false

# Heqet Functions / Injectors:
generators:
  # Vault Secret Injector
  vault: true

# App Definitions that will be managed in ArgoCD
apps:
  # Heqet
  - name: heqet
    path: .
    repoURL: https://github.com/nold360/heqet
    targetRevision: test
    syncWave: "-1"
    selfHeal: true

  # ArgoCD - Continous Deployment from Git
  - name: argocd
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 3.1.1
    syncWave: "0"
    secrets:
      - name: argocd-secret
        keys:
          - admin.password
          - server.secretkey
    
  # Vault
  - name: vault
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.11.0
    syncWave: "-3"
    parameters:
      - name: ui.enabled
        value: "true"
      - name: global.psp.enabled
        value: "true"
      - name: server.networkPolicy.enabled
        value: "true"
      - name: server.dev.enabled
        value: "false"
      - name: standalone.enabled
        value: "true"

  # Vault Secret Operator for automatic Secret injection
  - name: vault-secrets-operator
    repoURL: https://ricoberger.github.io/helm-charts
    chart: vault-secrets-operator
    targetRevision: 1.14.2
    syncWave: "-2"

  # Loki / Grafana / Promtail Stack for Logging & Metrics
  - name: loki-stack
    repoURL: https://grafana.github.io/helm-charts
    chart: loki-stack
    targetRevision: 2.3.1
    secrets:
      - name: loki-stack-grafana
        keys:
          - admin-user
          - admin-password
 
  # Object Storage
  - name: minio
    repoURL: https://charts.bitnami.com/bitnami
    chart: minio
    targetRevision: 6.7.2
    parameters:
     - name: global.minio.existingSecret
       value: minio-secret
     - name: ingress.enabled
       value: "true"
     - name: ingress.hostname
       value: minio.k3s
     - name: image.debug
       value: "true"
    secrets:
      - name: minio-secret
        keys:
          - access-key
          - secret-key
 
  # PiHole
  - name: pihole
    repoURL: https://mojo2600.github.io/pihole-kubernetes
    chart: pihole
    targetRevision: 1.8.34
    secrets:
      - name: pihole-admin
        keys:
          - password

  # Backup Server
  - name: backup-lan
    repoURL: https://github.com/lib42/charts.git
    path: charts/borgserver
    targetRevision: dev

  - name: backup-dmz
    repoURL: https://github.com/lib42/charts.git
    path: charts/borgserver
    targetRevision: dev

  # Apps...
  - name: folding
    #repoURL: https://pcktdmp.github.io/charts
    #chart: fahclient
    #targetRevision: 2.5.5
    repoURL: https://github.com/Nold360/charts-2/
    path: fahclient
    targetRevision: f_ingress
    parameters:
      - name: fahClient.user
        value: nold
      - name: fahClient.team
        value: "236833"
      - name: ingress.vhost
        value: folding.k3s
      - name: ingess.enabled
        value: "true"
      - name: resources.limits.cpu
        value: "8"
      - name: resources.limits.memory
        value: 1Gi


  # Polaris - Scan cluster for stuff
  - name: polaris
    repoURL: https://charts.fairwinds.com/stable
    chart: polaris
    targetRevision: 3.1.1

  # Deluge & OpenVPN-Client
  - name: deluge
    repoURL: https://github.com/lib42/charts.git
    path: charts/deluge-openvpn
    targetRevision: f_deluge
    secrets:
      - name: vpn-config
        keys:
          - ca.crt
          - auth.txt
          - client.ovpn
