# Install Custom Ressource Definitions?
installCRDs: true

# Default values that are used for creating ArgoCD `Application` definitions
defaults:
  project: "default"
  server: https://kubernetes.default.svc
  automated:
    prune: true
    selfHeal: false

# Heqet Functions / Injectors:
generators:
  # Vault Secret Injector
  vault: true

  # Use predfined NetworkPolices in Apps/Namespaces
  networkpolicy: true

# Define your NetworkPolicies here
networkpolicies:
  # Allow DNS to all Namespaces, deny everything else
  allow-dns:
    podSelector: {}
    policyTypes:
    - Egress
    egress:
    - ports:
      - port: 53
        protocol: UDP
      to:
      - namespaceSelector: {}

# App Definitions that will be managed in ArgoCD
apps:
  # Heqet
  - name: heqet
    path: .
    repoURL: https://github.com/nold360/heqet
    targetRevision: test
    syncWave: "-1"
    selfHeal: true

  # ArgoCD - Continous Deployment from Git
  - name: argocd
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 3.1.1
    syncWave: "0"
    secrets:
      - name: argocd-secret
        keys:
          - admin.password
          - server.secretkey
    
  # Vault
  - name: vault
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.10.0
    syncWave: "-3"
    parameters:
      - name: ui.enabled
        value: true
      - name: global.psp.enabled
        value: true
      - name: server.networkPolicy.enabled
        value: true
      - name: server.dev.enabled
        value: false
      - name: standalone.enabled
        value: true

  # Vault Secret Operator for automatic Secret injection
  - name: vault-secrets-operator
    repoURL: https://ricoberger.github.io/helm-charts
    chart: vault-secrets-operator
    targetRevision: 1.14.2
    syncWave: "-2"
