heqet:
  defaults:
    project: "default"
    repoURL: https://github.com/nold360/heqet
    server: https://kubernetes.default.svc
    automated:
      prune: true
      selfHeal: true

  apps:
      # We can even manage ArgoCD & declare values here :)
    - name: argocd
      repoURL: https://github.com/argoproj/argo-helm
      path: charts/argo-cd
      values:
        - name: dex.enabled
          value: false
    
    - name: heqet
      namespace: argocd
      path: charts/heqet

    - name: jaeger
      path: charts/jaeger-operator
      repoURL: https://github.com/jaegertracing/helm-charts
      targetRevision: HEAD
      values:
        - name: jaeger.create
          value: true

    - name: traefik-ingress
      path: traefik
      repoURL: https://github.com/containous/traefik-helm-chart
 
    - name: vault
      repoURL: https://github.com/hashicorp/vault-helm
      values:
        - name: server.dev.enabled
          value: "true"
        - name: server.ingress.enabled
          value: "true"
        - name: ui.enabled
          value: true

    - name: kubernetes-dashboard
      path: charts/kubernetes-dashboard
    - name: loki-stack
      path: charts/loki-stack
    - name: sync-waves
      path: charts/sync-waves
