heqet:
  defaults:
    project: "default"
    repoURL: https://github.com/nold360/heqet
    server: https://kubernetes.default.svc
    automated:
      prune: true
      selfHeal: false
  acme:
    email: nold@gnu.one

  apps:
      # We can even manage ArgoCD & declare values here :)
    - name: argocd
      repoURL: https://github.com/argoproj/argo-helm
      path: charts/argo-cd
      values:
        - name: dex.enabled
          value: false
        - name: server.ingress.enabled
          value: true
        - name: server.ingress.hosts
          value: [ argocd.heqet.gnu.one ]
        - name: server.logLevel
          value: "debug"
        - name: controller.logLevel
          value: "debug"
        - name: repoServer.logLevel
          value: "debug"
    
    - name: heqet
      namespace: argocd
      path: charts/heqet

    - name: jaeger
      path: charts/jaeger
      repoURL: https://github.com/jaegertracing/helm-charts
      targetRevision: HEAD
      values:
        - name: query.ingress.enabled
          value: true
        - name: query.ingress.hosts
          value: [ jaeger.heqet.gnu.one ]

    - name: nginx-ingress
      repoURL: https://github.com/kubernetes/ingress-nginx
      path: charts/ingress-nginx
      values:
        - name: controller.admissionWebhooks.enabled
          value: false
        - name: controller.admissionWebhooks.patch.enabled
          value: false
        - name: rbac.create
          value: true
        - name: controller.publishService.enabled
          value: true
        - name: controller.image.repository
          value: bitnami/nginx-ingress-controller
#     defaultBackend.enabled

    - name: cert-manager
      repoURL: https://github.com/jetstack/cert-manager
      path: deploy/charts/cert-manager
      values:
        - name: acme.server
          value: https://acme-staging-v02.api.letsencrypt.org/directory
        - name: acme.email
          value: nold@gnu.one
        - name: installCRDs
          value: true
#        - name: image.repository
#          value: bitnami/cert-manager
        - name: image.tag
          value: v0.15.1
        - name: webhook.image.tag
          value: v0.15.1
#        - name: webhook.enabled
#          value: false
#        - name: cainjector.enabled
#          value: false
   
    - name: vault
      repoURL: https://github.com/hashicorp/vault-helm
      values:
        - name: server.dev.enabled
          value: "true"
        - name: server.ingress.enabled
          value: "true"
        - name: server.ingress.hosts
          value: [ vault.heqet.gnu.one ]
        - name: ui.enabled
          value: true

    - name: kubernetes-dashboard
      path: stable/kubernetes-dashboard
      repoURL: https://github.com/helm/charts
      values:
        - name: ingress.enabled
          value: true
        - name: ingress.hosts
          value: [ dashboard.heqet.gnu.one ]

    - name: loki-stack
      path: charts/loki-stack
