heqet:
  defaults:
    project: "default"
    repoURL: https://github.com/nold360/heqet
    server: https://kubernetes.default.svc
    automated:
      prune: true
      selfHeal: true

  apps:
      # We can even manage ArgoCD & declare values here :)
    - name: argocd
      repoURL: https://github.com/argoproj/argo-helm
      path: charts/argo-cd
      values:
        - name: dex.enabled
          value: false
        - name: server.ingress.enabled
          value: true
        - name: server.ingress.hosts
          value: [ argocd.heqet.gnu.one ]
    
    - name: heqet
      namespace: argocd
      path: charts/heqet

    - name: jaeger
      path: charts/jaeger
      repoURL: https://github.com/jaegertracing/helm-charts
      targetRevision: HEAD
      values:
        - name: query.ingress.enabled
          value: true
        - name: query.ingress.hosts
          value: [ jaeger.heqet.gnu.one ]

    - name: traefik-ingress
      path: traefik
      repoURL: https://github.com/containous/traefik-helm-chart
      values:
        - name: acme.enabled
          value: true
        - name: acme.email
          value: "nold@gnu.one"
        - name: acme.onHostRule
          value: true
        - name: ssl.enabled
          value: true
        - name: ssl.enforced
          value: true
    
    - name: vault
      repoURL: https://github.com/hashicorp/vault-helm
      values:
        - name: server.dev.enabled
          value: "true"
        - name: server.ingress.enabled
          value: "true"
        - name: server.ingress.hosts
          value: [ vault.heqet.gnu.one ]
        - name: ui.enabled
          value: true

    - name: kubernetes-dashboard
      path: stable/kubernetes-dashboard
      repoURL: https://github.com/helm/charts
      values:
        - name: ingress.enabled
          value: true
        - name: ingress.hosts
          value: [ dashboard.heqet.gnu.one ]

    - name: loki-stack
      path: charts/loki-stack
