heqet:
  defaults:
    project: "default"
    repoURL: https://github.com/nold360/heqet
    server: https://kubernetes.default.svc
    automated:
      prune: true
      selfheal: true

  apps:
    - name: heqet
    - name: jaeger
      path: charts/jaeger-operator
      repoURL: https://github.com/jaegertracing/helm-charts
      targetRevision: HEAD
      values:
        - name: jaeger.create
          value: true

    - name: traefik-ingress
      path: traefik
      repoURL: https://github.com/containous/traefik-helm-chart
 
      # We can even declare values here :)
    - name: vault
      repoURL: https://github.com/hashicorp/vault-helm
      values:
        - name: server.dev.enabled
          value: "true"
        - name: server.ingress.enabled
          value: "true"
        - name: ui.enabled
          value: true

    - name: kubernetes-dashboard
      path: charts/kubernetes-dashboard
    - name: loki-stack
      path: charts/loki-stack
    - name: sync-waves
      path: charts/sync-waves
