config:
  description: Grafana, Prometheus and friends

apps:
  # Prometheus / Loki / Grafana / Promtail Stack for Logging & Metrics
  - name: prometheus
    namespace: prometheus
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 14.6.0
 
  - name: loki-stack
    existingNamespace: prometheus
    repoURL: https://grafana.github.io/helm-charts
    chart: loki-stack
    targetRevision: 2.4.1
    secrets:
      - name: loki-stack-grafana
        keys:
          - admin-user
          - admin-password
      - name: grafana-env
        keys:
          - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
