config:
  description: Arrr I'm a pirate!
  syncWave: 100
  repo: k8s-at-home
apps:
- name: ombi
  namespace: ombi
  chart: ombi
  targetRevision: 11.0.1
- name: jackett
  namespace: jackett
  chart: jackett
  targetRevision: 11.1.1
- name: sonarr
  namespace: sonarr
  chart: sonarr
  targetRevision: 15.1.0
- name: radarr
  namespace: radarr
  chart: radarr
  targetRevision: 15.0.3
- name: lidarr
  namespace: lidarr
  chart: lidarr
  targetRevision: 12.0.1
- name: bazarr
  chart: bazarr
  targetRevision: 10.0.0
- name: unpackerr
  chart: unpackerr
  targetRevision: 5.0.0
