aggregator:
  enabled: false

  
forwarder:
  configMapFiles:
    fluentd-output.conf: |
      # Throw the healthcheck to the standard output instead of forwarding it
      <match fluentd.healthcheck>
        @type stdout
      </match>

      # Forward all logs to elastic
      <match **>
        @type elasticsearch
        host elasticsearch-efk-es-http.efk.svc.cluster.local
        user "#{ENV['FLUENT_ELASTICSEARCH_USER']}"
        password  "#{ENV['FLUENT_ELASTICSEARCH_PASSWORD']}"
        port 9200
        logstash_format true
        <buffer>
          @type file
          path /opt/bitnami/fluentd/logs/buffers/logs.buffer
          flush_thread_count 2
          flush_interval 5s
        </buffer>
      </match>
    fluentd-inputs.conf: |
      # HTTP input for the liveness and readiness probes
      <source>
        @type http
        port 9880
        bind 0.0.0.0
      </source>
      # Get the logs from the containers running in the node
      <source>
        @type tail
        path /var/log/containers/*.log
        exclude_path /var/log/containers/*fluentd*.log
        pos_file /opt/bitnami/fluentd/logs/buffers/fluentd-docker.pos
        tag kubernetes.*
        read_from_head true
        <parse>
          @type regexp
          expression /^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<flags>[^ ]+) (?<message>.*)$/
          time_format %Y-%m-%dT%H:%M:%S.%N%:z
        </parse>
      </source>
      # enrich with kubernetes metadata
      <filter kubernetes.**>
        @type kubernetes_metadata
      </filter>

  extraEnv:
  - name: K8S_NODE_NAME
    value: hive
  - name: FLUENT_ELASTICSEARCH_USER
    value: elastic
  # Get Password from Elasticsearch Secret
  - name: FLUENT_ELASTICSEARCH_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elasticsearch-efk-es-elastic-user
        key: elastic

  extraVolumeMounts:
  - name: varlog
    mountPath: /var/log
