---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argocd
  namespace: kube-system
spec:
  chart: argo-cd
  repo: https://argoproj.github.io/argo-helm
  targetNamespace: argocd
  set:
    # Password: Admin
    configs.secret.argocdServerAdminPassword: "$2y$10$IuaM9Ad1mPMycjnStOdNc.wjRlLtI8448F/hS.eA0XJLH9r/ZwRv."
  valuesContent: |-
    controller:
      containerSecurityContext:
        capabilities:
          drop:
           - all
      readOnlyRootFilesystem: true
    dex:
      containerSecurityContext:
        capabilities:
          drop:
           - all
      readOnlyRootFilesystem: true
    redis:
      containerSecurityContext:
        capabilities:
          drop:
           - all
      readOnlyRootFilesystem: true
    server:
      containerSecurityContext:
        capabilities:
          drop:
           - all
      readOnlyRootFilesystem: true
      ingress:
        enabled: true
        hosts:
          - argocd.k3s
      extraArgs:
        - --insecure
    reposerver:
      containerSecurityContext:
        capabilities:
          drop:
           - all
      readOnlyRootFilesystem: true
