---
apiVersion: v1
kind: Namespace
metadata:
  name: heqet
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: heqet
  namespace: argocd
spec:
  destination:
    namespace: heqet
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/nold360/heqet'
    targetRevision: k3s
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
