apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: heqet
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/heqet
    repoURL: 'https://github.com/nold360/heqet'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
