apiVersion: cert-manager.io/v1alpha3
kind: ClusterIssuer
metadata:
  name: letsencrypt
#  annotations:
#    argocd.argoproj.io/sync-wave: "2"
spec:
  acme:
    server: {{ .Values.heqet.acme.server | default "https://acme-staging-v02.api.letsencrypt.org/directory" }}
    email: {{ .Values.heqet.acme.email | quote }}
    privateKeySecretRef:
      name: letsencrypt-clusterissuer
    solvers:
    - http01:
        ingress:
          class: nginx
