{{- range .Values.heqet.apps }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .namespace | default .name | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name | quote }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .project | default "default" }}
  destination:
    namespace: {{ .namespace | default .name | quote }}
    server: {{ .server | default $.Values.heqet.defaults.server }}
  source:
    path: {{ .path | default "." | quote }}
    repoURL: {{ .repoURL | default $.Values.heqet.defaults.repoURL | quote }}
    targetRevision: {{ .targetRevision | default "HEAD" | quote }}
    {{- if or .parameters .values }}
    helm:
      {{- if .parameters }}
      parameters:
        {{- range .parameters }}
        - name: {{ .name | quote }}
          value: {{ .value | quote }}
        {{- end }}
      {{- end }}
      {{- if .values }}
      values:
        {{- toYaml .values | indent 6 }}
      {{- end }}
    {{- end }}
  syncPolicy:
    automated:
      # FIXME: Open Issue: https://github.com/helm/helm/issues/8026
      prune: {{ $.Values.heqet.defaults.automated.prune | default false  }}
      selfHeal: {{ $.Values.heqet.defaults.automated.selfHeal | default false }}
{{- end }}
