apiVersion: certmanager.k8s.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: {{ .Values.heqet.acme.server | default "https://acme-staging-v02.api.letsencrypt.org/directory" }}
    email: {{ .Values.heqet.acme.email | quote }}
    privateKeySecretRef:
      name: letsencrypt-clusterissuer
    solvers:
    - http01:
        ingress:
          class: nginx
