controller:
  name: controller-external
  ingressClassResource:
    name: external
    enabled: true

  ingressClass: external
  kind: DaemonSet
  service:
    annotations:
      metallb.universe.tf/address-pool: external
  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"

podSecurityPolicy:
  enabled: true
