controller:
  name: controller-internal
  ingressClass: nginx
  kind: DaemonSet
  service:
    annotations:
      metallb.universe.tf/address-pool: internal
      metallb.universe.tf/allow-shared-ip: pihole
  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"

defaultBackend:
  enabled: true

podSecurityPolicy:
  enabled: false
