controller:
  admissionWebhooks:
    enabled: false
    patch:
      enabled: false
  publishService:
    enabled: false
  image:
    repository: bitnami/nginx-ingress-controller

rbac:
  create: true
