# NetworkPolicies predefinition
# rules can be added to groups. Groups or rules can be applied to projects.
#
networkPolicy:
  config:
    # Generate NetworkPolicy to allow communication inside of the project namespace?
    # Only gets applied when other networkpolices are active on the project
    allowNamespace: true

    # Default rules/groups to apply to projects
    default:
      groups: []
      rules: []

  # Group of rules
  groups:
    # Name: "internet", deny all but dns, proxy and ingress
    internet:
      - allow-dns
      - allow-proxy
      - allow-ingress

  rules:
  # Allow DNS to kube-system Namespaces, deny everything else
    allow-dns:
      podSelector: {}
      policyTypes:
      - Egress
      egress:
      - ports:
        - port: 53
          protocol: UDP
        to:
        - namespaceSelector:
            matchLabels:
              name: kube-system

    # Allow access to Kube-API
    allow-kubeapi:
      podSelector: {}
      policyTypes:
      - Egress
      egress:
      - ports:
        - port: 443
          protocol: TCP
        to:
        - namespaceSelector:
            matchLabels:
              name: kube-system

    # Allow access to internet proxy
    allow-proxy:
      podSelector: {}
      policyTypes:
      - Egress
      egress:
      - ports:
        - port: 80
          protocol: TCP
        - port: 3128
          protocol: TCP
        to:
        - namespaceSelector:
            matchLabels:
              app.heqet.gnu.one/project: proxy

    # Allow access from ingress-external
    allow-ingress:
      podSelector: {}
      policyTypes:
      - Ingress
      ingress:
      - from:
        - namespaceSelector:
            matchLabels:
              app.heqet.gnu.one/project: ingress
