repos:
  - name: argo
    url: https://argoproj.github.io/argo-helm
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: jetstack
    url: https://charts.jetstack.io
  - name: heqet
    url: https://git.nold.in/nold/heqet
    type: git
