apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentd-elastic
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: fluentd-elastic
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: charts/fluentd-elasticsearch
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
