apiVersion: v1
kind: Namespace
metadata:
  name: elastic-stack
  annotations:
    heket.gnu.one/app: true
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: linkerd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: fluentd-elastic
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
