---
apiVersion: v1
kind: Namespace
metadata:
  name: linkerd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    linkerd.io/inject: enabled
    sidecar.istio.io/inject: true
---
apiVersion: v1
kind: Namespace
metadata:
  name: heket-loki
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    linkerd.io/inject: enabled
    sidecar.istio.io/inject: true
---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    linkerd.io/inject: enabled
    sidecar.istio.io/inject: true
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubernetes-dashboard
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    linkerd.io/inject: enabled
    sidecar.istio.io/inject: true
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    linkerd.io/inject: enabled
    sidecar.istio.io/inject: false
