{{- range .Values.apps -}}
{{- if not .disabled }}
{{- if not .noCreateNamespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .namespace | default .name | quote }}
  labels:
    app.heqet.gnu.one/name: {{ .name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-42"
{{ with .annotations }}{{ toYaml .annotations | indent 4}}{{ end }}
{{- end }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name | quote }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app.heqet.gnu.one/name: {{ .name }}
    app.kubernetes.io/name: {{ .name }}
    app.kubernetes.io/part-of: heqet
  annotations:
    argocd.argoproj.io/sync-wave: {{ .syncWave | default "0" | quote }}
spec:
  project: {{ .project | default $.Values.defaults.project | default "heqet" }}
  destination:
    namespace: {{ .namespace | default .name | quote }}
    server: {{ .server | default $.Values.defaults.server | default "https://kubernetes.default.svc" }}
  source:
    path: {{ .path | default "" | quote }}
    repoURL: {{ .repoURL | default $.Values.defaults.repoURL | quote }}
    targetRevision: {{ .targetRevision | default $.Values.defaults.targetRevision | default "HEAD" | quote }}
    {{ if .chart }}chart: {{ .chart | quote }}{{ end }}
    helm:
      {{- with .parameters }}
      parameters:
{{ . | toYaml | indent 8 }}
      {{- end }}
{{- $values := $.Files.Get (printf "values.d/%s.yaml" .name ) | fromYaml | default dict }}
{{- with $values }}
      values: |
{{ toYaml $values | indent 8 }}
{{- end }}
  syncPolicy:
    automated:
      prune: {{ .prune | default $.Values.defaults.automated.prune | default "false"  }}
      selfHeal: {{ .selfHeal | default $.Values.defaults.automated.selfHeal | default "false" }}
{{- if .ignoreDiff }}
  ignoreDifferences:
{{ .ignoreDiff | toYaml | indent 4 }}
{{- end }}
{{- if $.Values.generators.vault }}{{- include "gen.secrets" . }}{{- end }}
{{- end }}
{{- end }}
