apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.defaults.project | default "heqet" }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  description: Heqet ArgoCD Bootstrapping Project
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
