# Jackett, Radarr, Sonarr, Lidarr & Ombi for Linux ISO's :P
config:
  namespace: arrstack
  description: Arrr I'm a pirate!
  syncWave: 100
  networkPolicy:
    groups:
    - internet
  labels:
    ich.mag/helm: true
 
apps:
- name: ombi
  repoURL: https://k8s-at-home.com/charts/
  chart: ombi
  targetRevision: 11.0.0

- name: jackett
  repoURL: https://k8s-at-home.com/charts/
  chart: jackett
  targetRevision: 11.0.0

- name: sonarr
  repoURL: https://k8s-at-home.com/charts/
  chart: sonarr
  targetRevision: 13.0.0

- name: radarr
  repoURL: https://k8s-at-home.com/charts/
  chart: radarr
  targetRevision: 13.0.0

- name: lidarr
  repoURL: https://k8s-at-home.com/charts/
  chart: lidarr
  targetRevision: 11.0.0
