heket:
  defaults:
    project: "default"
    repoURL: https://github.com/nold360/heket
    server: https://kubernetes.default.svc
    
  apps:
    - name: jaeger
      path: charts/jaeger-operator
      repoURL: https://github.com/lib42/helm-charts
      targetRevision: HEAD

    - name: traefik-ingress
      path: traefik
      repoURL: https://github.com/containous/traefik-helm-chart
 
      # We can even declare values here :)
    - name: heket-vault
      repoURL: https://github.com/hashicorp/vault-helm
      values:
        - name: server.dev.enabled
          value: "true"
        - name: server.ingress.enabled
          value: "true"
        - name: ui.enabled
          value: true

    - name: kubernetes-dashboard
      path: charts/kubernetes-dashboard
    - name: heket-loki
      path: charts/loki-stack
    - name: sync-waves
      path: charts/sync-waves
