spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/nold360/heket
    targetRevision: HEAD

heket:
  defaults:
    repoURL: https://github.com/nold360/heket
    server: https://kubernetes.default.svc
    
  apps:
    - name: heket-jaeger
      # FIXME: namespace: $name ?!
      path: charts/jaeger-operator
      repoURL: https://github.com/lib42/helm-charts
      targetRevision: HEAD
    - name: heket-vault
      repoURL: https://github.com/hashicorp/vault-helm
      spec:
        server:
          dev:
            enabled: true
    - name: dashboard
      path: charts/kubernetes-dashboard
    - name: heket-loki
      path: charts/loki-stack
    - name: nginx-ingress
      path: charts/nginx-ingress
    - name: sync-waves
      path: charts/sync-waves
