ingress:
  main:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: vault-issuer
    hosts:
    - host: readarr.dc
      paths:
      - path: /
        pathType: Prefix
    tls:
    - secretName: readarr-tls
      hosts:
      - readarr.dc

securityContext:
  privileged: false

persistence:
  config:
    enabled: true
    storageClass: local-path
    accessMode: ReadWriteOnce
    size: 1Gi
  media:
    enabled: true
    type: hostPath
    mountPath: /media
    hostPath: /data/media/ebooks
  downloads:
    enabled: true
    type: hostPath
    mountPath: /downloads
    hostPath: /data/torrent
    
